name: Copy Shared Files
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  wait:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.head_commit.message, '[Bot]') && !contains(github.event.head_commit.message, '[No Data Refresh]')}}
    steps:
      - name: Wait 30 secs before running
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

  Copy_includes:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy _includes
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_includes/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_sass:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy _sass
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_sass/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_assets:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy assets
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/assets/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_fonts:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy fonts
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/fonts/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_Post_Layout:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Post Layout
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_layouts/post.html'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/_layouts/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_Page_Layout:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Page Layout
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_layouts/page.html'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/_layouts/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_Shared_Pages:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Shared Pages
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_pages/Shared Content/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/_pages/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_Shared_Posts:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Shared Posts
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_posts/Shared Content/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/_posts/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_Shared_Images:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Shared Posts
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/images/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/images/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_404:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy 404
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/404.md'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_Favicon:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy favicon
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/favicon.ico'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_License:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy LICENSE
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/LICENSE'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_Readme:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy readme
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/README.md'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'

  Copy_Search:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy search.json
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/search.json'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'
          
  Copy_Funding:
    needs: wait
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy funding.yml
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/.github/FUNDING.yml'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/.github/'
          email: '41898282+github-actions[bot]@users.noreply.github.com'
          name: 'github-actions[bot]'
