name: Copy Shared Files
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Copy_includes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy _includes
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_includes/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'

  Copy_sass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy _sass
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_sass/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'

  Copy_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy assets
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/assets/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'

  Copy_fonts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy fonts
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/fonts/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'
