name: Copy Shared Files
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Copy_includes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy _includes
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_includes/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'

  Copy_sass:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy _sass
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_sass/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'

  Copy_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy assets
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/assets/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'

  Copy_fonts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy fonts
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/fonts/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/'

  Copy_Post_Layout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Post Layout
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_layouts/post.html'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/_layouts/'

  Copy_Page_Layout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Page Layout
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_layouts/page.html'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/_layouts/'

  Copy_Shared_Pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Shared Pages
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_pages/Shared Content/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/_pages/'

  Copy_Shared_Posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Shared Posts
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          src_path: '/_posts/Shared Content/'
          dst_owner: 'josh-justjosh'
          dst_repo_name: 'homepage'
          dst_path: '/_posts/'
